import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({

mainScreenFilmFlex:{
    flex:1,
    backgroundColor:"red"
},
mainScreenTopStyle:{
    flex:0.3,
    backgroundColor:"white"
},
mainScreenHintTextStyle:{
    fontSize:45,
    color:"teal"
},
touchOpPTF:{
    flex:0.5,
    backgroundColor:"teal",
    alignItems:"center",
    justifyContent:"center"
},
touchOpPTFTextStyle:{
    fontSize:35,
    color:"white"
},
textInputtouchOpStyle:{
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"white",
    fontSize:25
},
searchPanelViewStyle:{
    flex:0.8,
    backgroundColor:"teal",
    alignItems:"center",
    justifyContent:"center"
},
searchPanelTextStyle:{
    fontSize:25,
    alignItems:"center",
    justifyContent:"center"
},
mappedPieceViewStyle:{
    flex:0.7,
    alignItems:"center", 
    justifyContent:"center"
},
imageSourceStyle:{
    width:150,
    height:200,backgroundColor:"purple",
    borderRadius:90
},
movieNameTextStyle:{
    fontSize:25,
    color:"white",
    alignItems:"center",
    justifyContent:"center"
},
touchOpMS:{
    flex:0.5,
    backgroundColor:"#000000aa",
    borderRadius:10
},
modalView:{
    flex:1,
    backgroundColor:"#000000aa"
},
modalViewInside:{
    flex:0.6,
    backgroundColor:"#ffffff",
    margin:50,padding:40,
    borderRadius:20
},
XbuttontouchStyle:{
    alignItems:"flex-end"
},
})
export default styles